site_name: Mycelium Network Documentation
theme:
  logo: images/logo.png
  favicon: images/favicon.ico
  name: material
  language: en
  features:
    - instant
    - tabs
  palette:
    primary: blue grey
    accent: blue grey

repo_name: mycelium-network/mycelium-api
repo_url: https://github.com/mycelium-network/mycelium-api

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mycelium-network
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MyceliumNet
markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde